/*
Problem 1 — Easy
Get the full name of all employees (first name + last name as one column called full_name), 
their job title, and the country they work in. Sort the results by last name A→Z.
Tables needed: employees
*/

select 
    Concat(FirstName , ' ' , LastName) as full_name,
    title as job_title,
    Country
from employees
order by LastName asc;

/*
Problem 2 — Easy
Get a list of all unique countries that our customers are from. Sort them alphabetically.
Tables needed: customers
*/

select
    DISTINCT Country
from customers
order by Country;

/*
Problem 3 — Easy/Medium

Get all orders that were shipped to Germany or France. Show the OrderID, CustomerID, ShipCountry and OrderDate. Sort by OrderDate oldest to newest.

Tables needed: orders
*/
select
    OrderID, CustomerID, ShipCountry , OrderDate
FROM orders
where shipCountry = 'Germany' OR shipCountry = 'France'
order by orderDate asc;

/*Problem 4 — Medium

Find the total number of orders placed by each customer. 
Show the CustomerID and call the count column total_orders. 
Only show customers who have placed more than 5 orders. Sort by total_orders highest to lowest.

Tables needed: orders
*/

select
    customerid,
    count(*) total_orders
FROM orders
GROUP BY CustomerID
HAVING count(*) > 5
ORDER BY total_orders DESC;

/*
SQL — Problem 5 — Medium

Find the total revenue generated by each product. Revenue per order line = UnitPrice * Quantity * (1 - Discount). 
Show ProductID and total_revenue rounded to 2 decimal places. Sort by total_revenue highest to lowest. Only show products with total revenue above 5000.

Tables needed: order_details
*/
select 
    DISTINCT ProductID,
    round(sum((UnitPrice * Quantity * (1 - Discount))),2) as total_Revenue
from order_details
GROUP BY 1
having total_Revenue > 5000
ORDER BY total_Revenue desc;

/*
SQL — Problem 6 — Medium

Show each employee's full name (as full_name) and the total number of orders they handled (as total_orders). Sort by total_orders highest to lowest.

Tables needed: orders, employees
*/

select
    concat(e.FirstName , ' ', e.LastName) as emp_fullname,
    count(orderID) as total_orders
from orders o
LEFT join employees e ON o.employeeID = e.EmployeeID
group by 1
order by 2 desc;