/*
Problem 1 — Easy
Get the full name of all employees (first name + last name as one column called full_name), 
their job title, and the country they work in. Sort the results by last name A→Z.
Tables needed: employees
*/

select 
    Concat(FirstName , ' ' , LastName) as full_name,
    title as job_title,
    Country
from employees
order by LastName asc;

/*
Problem 2 — Easy
Get a list of all unique countries that our customers are from. Sort them alphabetically.
Tables needed: customers
*/

select
    DISTINCT Country
from customers
order by Country;

/*
Problem 3 — Easy/Medium

Get all orders that were shipped to Germany or France. Show the OrderID, CustomerID, ShipCountry and OrderDate. Sort by OrderDate oldest to newest.

Tables needed: orders
*/
select
    OrderID, CustomerID, ShipCountry , OrderDate
FROM orders
where shipCountry = 'Germany' OR shipCountry = 'France'
order by orderDate asc;

/*Problem 4 — Medium

Find the total number of orders placed by each customer. 
Show the CustomerID and call the count column total_orders. 
Only show customers who have placed more than 5 orders. Sort by total_orders highest to lowest.

Tables needed: orders
*/

select
    customerid,
    count(*) total_orders
FROM orders
GROUP BY CustomerID
HAVING count(*) > 5
ORDER BY total_orders DESC;

/*
SQL — Problem 5 — Medium

Find the total revenue generated by each product. Revenue per order line = UnitPrice * Quantity * (1 - Discount). 
Show ProductID and total_revenue rounded to 2 decimal places. Sort by total_revenue highest to lowest. Only show products with total revenue above 5000.

Tables needed: order_details
*/
select 
    ProductID,
    round(sum((UnitPrice * Quantity * (1 - Discount))),2) as total_Revenue
from order_details
GROUP BY 1
having total_Revenue > 5000
ORDER BY total_Revenue desc;

/*
SQL — Problem 6 — Medium

Show each employee's full name (as full_name) and the total number of orders they handled (as total_orders). Sort by total_orders highest to lowest.

Tables needed: orders, employees
*/

select
    concat(e.FirstName , ' ', e.LastName) as emp_fullname,
    count(orderID) as total_orders
from orders o
LEFT join employees e ON o.employeeID = e.EmployeeID
group by 1
order by 2 desc;



/*
SQL — Problem 7 — Medium

Show the top 5 products by total quantity sold. Display ProductID, ProductName and total_quantity_sold. 
Sort highest to lowest.

Tables needed: order_details, products
*/

select 
    p.ProductID , p.ProductName , sum(od.Quantity) as total_quantity_sold
from order_details od
LEFT JOIN products p on od.ProductID = p.ProductID
GROUP BY 1,2
ORDER BY 3 desc
LIMIT 5;
/*
SQL — Problem 8 — Medium/Hard

For each category, show the CategoryName, total number of products (total_products), 
average product unit price (avg_price) rounded to 2 decimal places, and the most expensive product price (max_price). 
Sort by avg_price highest to lowest.

Tables needed: products, categories
*/

select
    c.categoryName , count(p.ProductID) as total_products , round(avg(p.UnitPrice),2) as avg_price ,
    max(p.UnitPrice) as max_price
from products p
LEFT JOIN categories c on p.CategoryID = c.categoryID
GROUP BY 1
ORDER BY 3 desc;

/*
🗄️ SQL — Problem 9 — Medium/Hard

For each order, show the OrderID, CustomerID, OrderDate, Freight and the running total of freight (cumulative sum) ordered by OrderDate. Call the running total running_freight.

Tables needed: orders
Hint: This is your first window function —SUM() OVER (ORDER BY ...)
*/

SELECT 
    orderID ,
    customerID,
    orderDate,
    freight,
    sum(freight) over(ORDER BY orderDate, orderID) as running_freight
from orders;

/*
🗄️ SQL — Problem 10 — Hard

Rank all products by their total revenue (use UnitPrice * Quantity * (1 - Discount)) within each category. 
Show CategoryID, ProductID, ProductName, total_revenue rounded to 2 decimal places, and revenue_rank. Only show rank 1, 2 and 3 per category.

Tables needed: order_details, products
Hint: RANK() OVER (PARTITION BY ... ORDER BY ...) — this is the heart of window functions. PARTITION BY is like GROUP BY but for window functions.
In DuckDB/Snowflake you can filter on window function results using QUALIFY. 👀
*/

with revenue_cte as (
select
    p.CategoryID , p.ProductID , p.ProductName , 
    round(sum(((od.UnitPrice * od.Quantity) * (1-od.Discount))),2) as total_revenue
from order_details od
LEFT JOIN products p ON od.ProductID=p.ProductID
GROUP BY 1,2,3
)
select
    *,
    rank() OVER(PARTITION BY CategoryID order by total_revenue DESC) rank_revenue
from revenue_cte
QUALIFY rank_revenue <= 3;



/*
 SQL — Problem 11 — Hard

Using a CTE, find all customers who have never placed an order. Show their CustomerID and CompanyName.

Tables needed: customers, orders
Hint: Think about LEFT JOIN + filtering for NULL, or use a subquery with NOT IN / NOT EXISTS.
*/

with cust_cte as (
select
    o.orderID,
    c.customerID ,
    c.CompanyName
    FROM customers c
LEFT JOIN orders o ON c.CustomerID = o.customerID
)
select
    *
from cust_cte
where orderID IS NULL;

/*
SQL — Problem 12 — Hard

Write a query to find the month-over-month revenue for the year 1997. Show month, monthly_revenue rounded to 2 decimal places, and previous_month_revenue.

Tables needed: orders, order_details
Hint: You'll need LAG() window function — LAG(column) OVER (ORDER BY ...) gets the previous row's value. Use MONTH(OrderDate) to extract the month.
*/

select 
    month(o.orderDate) as ordermonth,
    round(sum(((od.UnitPrice * od.Quantity) * (1-od.Discount))),2) as total_revenue,
    lag(total_revenue) OVER(order by ordermonth) as previous_month_revenue
FROM 
orders o
LEFT JOIN order_details od
ON o.orderID = od.OrderID
where YEAR(o.orderDate) = '1997'
GROUP BY 1 ;
