---------
---------
--DATABASE EXPLORATION
---------
---------



-- Explore All objects in the database
select * from INFORMATION_SCHEMA.TABLES;

-- Selecting Distinct tables names
select DISTINCT TABLE_NAME from INFORMATION_SCHEMA.TABLES;

-- Explre All Columns in the database
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers';

---------
---------
--DIMENSION EXPLORATION
---------
---------

-- Explore All the countries our customers are from
select distinct country from gold.dim_customers;

-- Explore All product categories "The Major Divisions"
select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3;


---------
---------
--DATE EXPLORATION
---------
---------


-- Find the date of the first and last order
--How many years of sales are available in the data?
select
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    EXTRACT (YEAR FROM MAX(order_date)) -  EXTRACT(YEAR FROM MIN(order_date)) AS order_range_years
FROM gold.fact_sales;

-- Find the youngest and oldest customers
SELECT
    MIN(birthdate) AS oldest_customer_birthdate,
    MAX(birthdate) AS youngest_customer_birthdate,

    EXTRACT(YEAR FROM AGE(CURRENT_DATE, MIN(birthdate))) 
        AS oldest_age,

    EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAX(birthdate))) 
        AS youngest_age,

    EXTRACT(YEAR FROM MAX(birthdate))
    - EXTRACT(YEAR FROM MIN(birthdate))
        AS age_range_years

FROM gold.dim_customers;


---------
---------
--Measures EXPLORATION
---------
---------

select * from gold.fact_sales limit 5;

--Find the total sales
select sum(sales_amount) as total_sales from gold.fact_sales;
-- Find how many items are sold
select sum(quantity) as total_items_sold from gold.fact_sales;
-- Find the average selling price
select avg(price) as average_selling_price from gold.fact_sales;
-- Find the total number of orders
select count(DISTINCT order_number) as total_orders from gold.fact_sales;
-- Find the total number of products
select count(product_key) as total_products from gold.fact_sales;
-- Find the total number of customers
select count(customer_key) as total_customers from gold.fact_sales;
-- Find the total number of customers that has placed an order
select count(DISTINCT customer_key) as total_customers_with_orders from gold.fact_sales;


-- Generate a report that shows all key metrics of the business

select 'Total Sales' as measure_name , sum(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL 
select 'Total Quantity' as measure_name , sum(quantity) AS measure_value FROM gold.fact_sales
UNION ALL 
select 'Average Price' as measure_name , avg(price) AS measure_value FROM gold.fact_sales
UNION ALL 
select 'Total Orders' as measure_name , count(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL 
select 'Total Products' as measure_name , count(product_key) AS measure_value FROM gold.fact_sales
UNION ALL 
select 'Total Customers' as measure_name , count(DISTINCT customer_key) AS measure_value FROM gold.fact_sales;


---------
---------
--Magnitude Analysis
---------
---------


-- Find total customers by countries

select country, count(DIStiNCT customer_key) as total_customers 
from gold.dim_customers
group by 1
order by 2 desc;

-- Find total customers by gender

select gender, count(distinct customer_key) as total_customers
from gold.dim_customers
group by 1
order by 2 desc;

-- Find total products by category

select category, count(DISTINCT product_key) as total_products
from gold.dim_products
group by 1
order by 2 desc;

-- What is the average costs in each category?

select category , avg(cost) as average_cost
from gold.dim_products
group by 1
order by 2 desc;

-- What is the total revenue generated for each category?

select p.category, sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT join gold.dim_products p 
ON f.product_key = p.product_key
group by 1
order by 2 desc;


-- Find total revenue is generated by each customer

select 
    c.customer_id, c.first_name, c.last_name,
   sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT join gold.dim_customers c
ON f.customer_key = c.customer_key
group by 1,2,3
order by 4 desc;

-- What is the distribution of sold items across countries?
select 
    c.country,
   sum(f.quantity) as total_distribution
from gold.fact_sales f
LEFT join gold.dim_customers c
ON f.customer_key = c.customer_key
group by 1
order by 2 desc;

-- which 5 products generate the highest revenue?
select p.product_name,p.subcategory, sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT join gold.dim_products p 
ON f.product_key = p.product_key
group by 1,2
order by 2 desc
limit 5;

-- RANK func
select * from (
    select 
        p.product_name,sum(f.sales_amount) as total_revenue,
        row_number() OVER(order by sum(f.sales_amount) DESC) as rank_products
    from gold.fact_sales f
    LEFT join gold.dim_products p 
    ON f.product_key = p.product_key
    group by 1
) t
where rank_products <= 5;



-- what are the 5 worst performing products in terms of sales?
select p.product_name, p.subcategory,sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT join gold.dim_products p 
ON f.product_key = p.product_key
group by 1,2
order by 2
limit 5;


--- Find the top-10 customers who have generated the highest revenue and 3 customers with the fewest orders placed
select 
    c.customer_id, c.first_name, c.last_name,
   sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT join gold.dim_customers c
ON f.customer_key = c.customer_key
group by 1,2,3
order by 4 desc
limit 10;

-- lowest 3 customers with fewest orders placed

select 
    c.customer_id, c.first_name, c.last_name,
   count(DISTINCT order_number) as total_orders
from gold.fact_sales f
LEFT join gold.dim_customers c
ON f.customer_key = c.customer_key
group by 1,2,3
order by 4 asc
limit 3;
